---
- hosts: all
  tasks:

  - name: Creating /u02 directory
    file: path=/u02 state=directory owner=vagrant group=vagrant
    become: true

  - name: Copying ifcfg-ens33 
    copy: src=/vagrant/scripts/ifcfg-ens33-soa1 dest=/etc/sysconfig/network-scripts/ifcfg-ens33 owner=root group=root mode=0644 remote_src=yes
    become: true

  - name: Setting hostname
    hostname: name=soavh01
    become: true

  - name: Updtaing /etc/samba/smb.conf
    copy: src=/vagrant/scripts/smb.conf dest=/etc/samba/smb.conf mode="u=rw,g=r,o=r"
    become: true

  - name: Reloading SMB service
    systemd: name=smb state=restarted enabled=true
    become: true

  - name: Reloading network service
    systemd: name=network state=restarted
    become: true
