---
- hosts: all
  become: true
  tasks:
  
  #Este repo lo necesitamos para docker
  - name: Enabling Yum Repositories
    command: "yum-config-manager --enable ol7_addons"
    
  - name: Installing packages
    yum: 
      state=installed name={{ item }}
    with_items:
      - yum-utils
      - lvm2
      - sysstat
      - dos2unix
      - nano
      - zip
      - unzip
      - samba 
      - samba-winbind
      - nfs-utils
      - docker-engine

  - name: Converting EOL files from DOS to UNIX
    command: find /vagrant/scripts -name "*" -exec /usr/bin/dos2unix {} \;

  - name: Adding vagrant to docker group
    user: name=vagrant groups=docker append=yes

  - name: Enabling docker service
    systemd: name=docker state=started enabled=true
    
  - name: Updtaing /etc/hosts
    copy: src=/vagrant/scripts/hosts dest=/etc/hosts mode="u=rw,g=r,o=r"

  # Samba y directorios compartidos
  - name: Creating /var/nfs/u01/oracle/config directory
    file: path=/var/nfs/u01/oracle/config state=directory owner=vagrant group=vagrant        

  - name: Adding user vagrant to SMB
    shell: test `pdbedit -w -L | awk -F":" '{ print $1 }' | grep 'vagrant$' | wc -l` -eq 1 || echo -ne "vagrant\nvagrant\n" | smbpasswd -s -a vagrant

  - name: Updtaing /etc/samba/smb.conf
    copy: src=/vagrant/scripts/smb-services.conf dest=/etc/samba/smb.conf mode="u=rw,g=r,o=r"
    
  - name: Updtaing /etc/exports
    copy: src=/vagrant/scripts/exports dest=/etc/exports mode="u=rw,g=r,o=r"
    
  - name: Enabling ip_forward
    sysctl: name=net.ipv4.ip_forward value=1 sysctl_set=yes state=present reload=yes    
    
  - name: Copying ifcfg-ens33
    copy: src=/vagrant/scripts/ifcfg-ens33-services dest=/etc/sysconfig/network-scripts/ifcfg-ens33 owner=root group=root mode=0644 remote_src=yes

  - name: Setting hostname
    hostname: name=services

  - name: Reloading network service
    systemd: name=network state=restarted    

  - name: Reloading SMB service
    systemd: name=smb state=restarted enabled=true
    
  - name: Reloading NFS service
    systemd: name=nfs-server state=restarted enabled=true
