---
- hosts: all
  become: yes
  tasks:

  - name: Converting EOL files from DOS to UNIX
    command: find /vagrant/scripts -name "*" -exec /usr/bin/dos2unix {} \; 
    
  - name: Installing packages
    yum: 
      state=installed name={{ packages }}
    vars:
     packages:
      # Linux Operating System Requirements: http://docs.oracle.com/cd/E23104_01/sysreqs1221/sysrs.htm#BABJBCAI
      # http://www.zulqarnainhayat.com/wp-content/uploads/2017/10/weblogic-steps-1.txt
      - compat-libcap1
      - compat-libstdc++-33.x86_64
      - compat-libstdc++-33.i686
      - gcc
      - gcc-c++
      - glibc.i686
      - glibc-devel.x86_64
      - libaio-devel.x86_64
      - libstdc++-devel.x86_64
      - ksh
      - sysstat
      - dos2unix
      - dejavu-sans-fonts
      # We need these libraries in order to execute X clients
      - xorg-x11-utils
      - xorg-x11-apps
      - xorg-x11-xauth
      # Helper libraries in order to execute X clients
      - gtk2
      - rng-tools
      - nano
      - mesa-dri-drivers
      - zip
      - unzip
      - samba 
      - samba-winbind
      - nfs-utils
      - lsof      

  - name: Enabling rngd
    systemd: name=rngd state=started enabled=yes
    
  - name: Updating /etc/hosts
    copy: src=/vagrant/scripts/hosts dest=/etc/hosts mode="u=rw,g=r,o=r"    

  # Preparing directories
  - name: Creating /u01 directory
    file: path=/u01 state=directory owner=vagrant group=vagrant

  - name: Creating /u02 directory
    file: path=/u02 state=directory owner=vagrant group=vagrant
    
  # Installing JDK
  - name: Extracting JDK
    unarchive: src=/mnt/installers/jdk-8u152-linux-x64.tar.gz dest=/opt remote_src=yes owner=root group=root creates=/opt/jdk1.8.0_152/bin/java

  - name: Creating JDK sym link
    file: src=/opt/jdk1.8.0_152 dest=/opt/jdk_latest owner=root group=root state=link

  # Updating .bash_profile and .bashrc
  - name: Copying .bash_profile
    copy: src=/vagrant/scripts/.bash_profile dest=/home/vagrant/.bash_profile mode="u=rw,g=r,o=r"
    
  - name: Copying .bashrc
    copy: src=/vagrant/scripts/.bashrc dest=/home/vagrant/.bashrc mode="u=rw,g=r,o=r"  
    
  # Creating Oracle Inventory and Installing common infrastructure  
  - name: Creating Oracle Inventory
    command: /vagrant/scripts/createCentralInventory.sh
    args:
      creates: /etc/oraInst.loc

  - name: Installing Oracle FMW Infrastructure (12.2.1.3.0)
    command: /opt/jdk_latest/bin/java -jar /mnt/installers/fmw_12.2.1.3.0_infrastructure.jar -silent -responseFile /vagrant/scripts/fmw_infraestructure.resp
    become_user: vagrant
    args:
      creates: /u01/oracle/product/fmw
    
  # Sharing folders
  - name: Adding user vagrant to SMB
    shell: test `pdbedit -w -L | awk -F":" '{ print $1 }' | grep 'vagrant$' | wc -l` -eq 1 || echo -ne "vagrant\nvagrant\n" | smbpasswd -s -a vagrant

  - name: Updating /etc/samba/smb.conf
    copy: src=/vagrant/scripts/smb.conf dest=/etc/samba/smb.conf mode="u=rw,g=r,o=r"

  - name: Reloading SMB service
    systemd: name=smb state=restarted enabled=true
    
  - name: Mounting NFS /u01/oracle/config directory
    mount: fstype=nfs name=/u01/oracle/config src='services:/var/nfs/u01/oracle/config' state=mounted
