# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|


  config.vm.define :soa1 do |soa1|
    soa1.vm.box = "bento/oracle-7.4"
	soa1.vm.network "private_network", auto_config: false
	
    soa1.vm.provision "ansible_local" do |ansible|
		ansible.playbook = "playbook-soa-common.yml"
    end	
	
	soa1.vm.provision "ansible_local" do |ansible|
		ansible.playbook = "playbook-soa1.yml"
	end
  end    

  config.vm.define :soa2 do |soa2|
    soa2.vm.box = "bento/oracle-7.4"
	soa2.vm.network "private_network", auto_config: false
	
    soa2.vm.provision "ansible_local" do |ansible|
		ansible.playbook = "playbook-soa-common.yml"
    end	
	
	soa2.vm.provision "ansible_local" do |ansible|
		ansible.playbook = "playbook-soa2.yml"
	end		
  end
  
  config.vm.define :services do |services|
	services.vm.box = "bento/centos-7.4"
	services.vm.network "private_network", ip: "192.168.40.50"
	
	services.vm.provision "ansible_local" do |ansible|
		ansible.playbook = "playbook-services.yml"
	end
  end  

  config.vm.synced_folder "D:/Download/Oracle/soa_bpm/12.2.1.3.0/vagrant_installers", "/mnt/12.2.1.3.0"
  config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", disabled: true

  config.ssh.forward_x11 = true  
  config.ssh.forward_agent = true

  config.vm.provider "vmware_workstation" do |vmware|
    vmware.gui = true
    vmware.vmx["memsize"] = "8192"
    vmware.vmx["numvcpus"] = "2"
	vmware.vmx["cpuid.corespersocket"] = "2"
	vmware.whitelist_verified = true
  end
  
end
