#! /bin/sh

set -e

if [ "$IFACE" = lo ]; then
	exit 0
fi


if [ "$MODE" != start ]; then
	exit 0
fi


if [ "$PHASE" != post-up ]; then
	exit 0
fi


if [ "$METHOD" = dhcp ]; then
	ip route delete default &> /dev/null 
fi


if [ "$METHOD" = static ]; then
	ip route add default via 192.168.2.1 &> /dev/null
fi


exit 0
