---
- hosts: all
  tasks:
  - name: Setting hostname
    hostname: name=debian-server
    become: true
    
  - name: Updtaing /etc/hosts
    copy: src=/vagrant/scripts/hosts dest=/etc/hosts mode="u=rw,g=r,o=r" 
    become: true
    
  - name: Copying default-gw 
    copy: src=/vagrant/scripts/default-gw dest=/etc/network/if-up.d owner=root group=root mode=0744 remote_src=yes
    become: true    
          
#  - name: Installing docker
#    shell: curl -fsSL get.docker.com | sudo sh
#    args:
#        creates: /usr/bin/docker
#  - name: Adding mauricio to docker group
#    user: name=mauricio groups=docker append=yes
#    become: true
#https://www.tecmint.com/apt-cache-server-in-ubuntu/
